default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: dux_soup_dev


test:
  <<: *default
  database: dux_soup_test

production:
  <<: *default
  database: dux_soup_prod
